apiVersion: 0.0.1
environments:
  test-env:
    destination:
      namespace: test-namespace
      server: https://35.197.120.104
    k8sVersion: v1.8.0
    path: test-env
  staging-argocd-demo:
    destination:
      namespace: default
      server: https://35.185.240.221
    k8sVersion: v1.8.0
    path: staging-argocd-demo
kind: ksonnet.io/app
name: test-app
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
